glg-public/gds-cc-screamer

checks/secrets-json-valid.js, test/secrets-json-valid.js
This check was previously more sensitive than AWS requires: https://docs.aws.amazon.com/AmazonECS/latest/developerguide/specifying-sensitive-data-secrets.html
I have slightly modified the regex to be more tolerant, and extended a test case to validate it.
=> be more tolerant of secret ARNs

checks/index.js, checks/no-carriage-return.js, test/no-carriage-return.js
Windows uses `CRLF` instead of `LF` for newlines. This is not allowed, so this check looks for `CR` and yells about it.
Added test coverage, and tested in the wild here: https://github.com/glg/cc-screamer-testing.s99/pull/5
=> No carriage return characters

checks/index.js, checks/no-aws-secrets.js, checks/template.js, test/no-aws-secrets.js
Adding a check that **warns** for the presence of `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`, and **fails** if there are actual secret values in the orders.
=> check for aws secrets

checks/index.js, checks/jwt-access-flags.js, checks/no-out-of-scope-vars.js, test/jwt-access-flags.js, test/no-out-of-scope-vars.js, util.js
This adds a check for the use of variables that are not defined within the orders file. Many services are used to relying on `.starphleet`, and so reference variables that are defined in the parent scope. This is not permitted in GDS, so we should block when we find it.
See it in action here: https://github.com/glg/cc-screamer-testing.s99/pull/8
=> Out of scope vars

checks/index.js, checks/use-cname.js, test/use-cname.js
Adds a check for the use of cluster dns like `s99.glgresearch.com`, and warns that the user should use a friendly CNAME (like `streamliner.glgresearch.com`) instead.
Tested live here: https://github.com/glg/cc-screamer-testing.s99/pull/8
=> check for cluster dns use

checks/no-sourcing.js, checks/service-name.js, test/deployment-line.js, test/healthcheck.js, test/https-only.js, test/jwt-access-flags.js, test/no-aws-secrets.js, test/no-debug-in-prod.js, test/no-duplicate-exports.js, test/no-out-of-scope-vars.js, test/no-sourcing.js, test/no-spaces-in-exports.js, test/policy-json-valid.js, test/secrets-in-orders.js, test/use-cname.js, test/valid-bash-subsitution.js
Improved test coverage of checks. Now full project is >91%:
```
-----------------------------|---------|----------|---------|---------|-------------------------------------------------
File                         | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s                               
-----------------------------|---------|----------|---------|---------|-------------------------------------------------
All files                    |   91.29 |    82.73 |    88.1 |   91.07 |                                                 
gds-cc-screamer             |       0 |        0 |       0 |       0 |                                                 
typedefs.js                |       0 |        0 |       0 |       0 | …
```
=> Even more tests

action.yml, checks/use-cname.js, index.js, test/fixtures/cluster-map.json, test/use-cname.js, typedefs.js, util/generic.js, util/index.js
This upgrades a previous check (Use CNAME). It now fetches the cluster map to provide accurate, cluster-specific url recommendations.
=> Smarter url swapping

checks/no-aws-secrets.js, test/no-aws-secrets.js
resolves #18
resolves #19 
This makes our AWS secrets check more specific. It will no longer flag things that aren't exported, and don't include `AWS` in the variable name
=> Stop flagging non-aws things as aws secrets

test/fqdn-required.js
Added test while investigating #45 
As I suspected, the quotes are a non-issue, and the problem was caused by a delay in updating the cluster map
=> add test to prove quotes don't matter

checks/secrets-exist.js, test/fixtures/cc1/test-service/policy.json, test/fixtures/cc1/test-service/secrets.json, test/fixtures/cc2/test-service/policy.json, test/fixtures/cc2/test-service/secrets.json, test/fixtures/cc2/test-service2/policy.json, test/fixtures/cc2/test-service2/secrets.json, test/fixtures/cc5/test-service/policy.json, test/fixtures/cc5/test-service/secrets.json, test/fixtures/cc5/test-service2/policy.json, test/fixtures/cc5/test-service2/secrets.json, test/fixtures/cc5/test-service3/policy.json, test/fixtures/cc5/test-service3/secrets.json, test/fixtures/cc5/test-service4/policy.json, test/fixtures/cc5/test-service4/secrets.json, test/fixtures/cc5/test-service5/policy.json, test/fixtures/cc5/test-service5/secrets.json, test/fixtures/issues51-53/policy.json, test/fixtures/issues51-53/secrets.json, test/no-carriage-return.js, test/policy-json-valid.js, test/secrets-exist.js, test/secrets-json-valid.js, test/test-service/policy.json, test/test-service/secrets.json, test/util/generic.js, test/util/text.js, util/generic.js
Resolves #51 
Resolves #52
This fixes some bugs related to handling secret arns that use the `-??????` suffix.
It also adds test coverage for the reported scenarios.
=> Secrets bug fixes

action.yml, index.js, util/github.js
Our new gds app tokens don't have the same trade-for-session workflow as the old starphleet ones.
=> Use new app token

checks/potential-secrets.js, test/potential-secrets.js
Ignores the following variables:
* SECRETS_AWS_REGION
* SECRETS_CREDENTIAL_SOURCE
* SECRETS_LOG_LEVEL
* SECRETS_NAMESPACE
=> ignore known variables with the word "secret" in them"

checks/max-services-per-cluster.js, test/max-services-per-cluster.js
resolves #80 
The limit of 100 services per cluster is because of a limit on the number of rules on an application load balancer. Jobs clusters don't have a load balancer, and are therefore unencumbered by this restriction.
=> skip max services check for jobs clusters

checks/deployment-line.js, checks/secrets-exist.js, test/deployment-line.js, test/secrets-exist.js
There are some situations where CC screamer will flag things as nonexistant, even if they exist. This is due to a stale cache in deployinator. Now, these messages will include instructions for refreshing the cache.
resolves #84
=> suggest refreshing the cache

checks/use-cname.js, test/use-cname.js
CC Screamer will now use deployinator to get the cluster-map, so it will always have the latest domain info
=> Use deployinator to fetch cluster-map

checks/double-quotes.js, checks/index.js, checks/potential-secrets.js, test/double-quotes.js
resolves #98
The root problem of that issue is that deployinator wrote the orders with multiple quotes. That issue has been resolved, and this pr adds a check for double-quoted values.
=> add check for double-quotes values

checks/deployment-line.js, checks/secrets-exist.js, test/secrets-exist.js
resolves #119 
When requesting ecr image tags and aws secret names from deployinator, the `aws_account_id` input will be used to query resources from the correct aws account
=> request information from non-default accounts

checks/potential-secrets.js, test/potential-secrets.js
resolves #131 
Adds an exception to the secrets checker for comma-separated lists, when that list does not contain secrets as items.
=> add exception for CSL

README.md, checks/double-quotes.js, checks/entrypoint-requires-cmd.js, checks/index.js, checks/valid-bash-substitution.js, checks/valid-json-arrays-in-bash.js, test/entrypoint-requires-cmd.js, test/valid-bash-substitution.js, test/valid-json-arrays-in-bash.js
This checks that CMD and ENTRYPOINT parse as JSON and contain parse as an Array.
It will present the following errors (and opts out of some other checks where these provide more appropriate messaging):
Parses as a string:
Does not parse as JSON:
ENTRYPOINT present without CMD:
=> Validation checks for CMD and ENTRYPOINT

checks/no-out-of-scope-vars.js, test/no-out-of-scope-vars.js
resolves #135
Check will now not flag single quotes expressions within a subshell
=> handle new edge case

checks/no-duplicate-exports.js, test/no-duplicate-exports.js
resolves #141 
Ambrose brings up a valid point that duplicate exports should not be a failing check, since it is technically valid bash. So, downgrading this to a "warning" level check.
=> make dupe exports a warning

checks/deployment-line.js, checks/entrypoint-requires-cmd.js, checks/healthcheck.js, checks/https-only.js, checks/no-duplicate-exports.js, checks/no-sourcing.js, checks/no-spaces-in-exports.js, checks/valid-bash-substitution.js, util/github.js
resolves #149, which occurs because  in every other place, we default path to orders path, but not in the case of problems existing outside of diff. I added a default, and made several checks more explicit
=> always specify path, even though we default it in some places

README.md, action.yml, checks/fqdn-lock.js, checks/index.js, index.js, test/all-checks-mounted.js, test/fqdn-lock.js, typedefs.js
resolves #153 
Adds a "check" that blocks deployments to specified FQDN. This is intended to be used during cluster re-balancing, when services are being migrated to a different cluster.
Also adds tests to verify that all checks are mounted, and mentioned by name in the readme.
=> Add a check that locks by fqdn

README.md, checks/potential-secrets.js, index.js, test/potential-secrets.js, typedefs.js, util/generic.js
resolves #176
The config object is now attached to the `inputs` object, allowing checks to implement individual configuration behavior. The first example of this is the `potentialSecrets` check will now have configurable exclusions.
[it works](https://github.com/glg/cc-screamer-testing.s99/pull/75)
=> Inject .ccscreamer.json into checks

checks/policy-json-valid.js, test/policy-json-valid.js
resolves #187 
Adds functionality to the IAM Policy validator that checks for duplicate `Sid` values within a policy, as this is not allowed per the IAM policy spec.
=> catch duplicate Sids

README.md, checks/deployment-line.js, test/deployment-line.js
Fixes: https://github.com/glg-public/gds-cc-screamer/issues/236
This introduces support for monorepo like apps that require a `ecr_repository_override` value in the workflow file. In the case above, the user had a need for an image that was somewhat nested ([see it here](https://github.com/glg/sl2-mono/blob/27d4a9c08ff864eeeba6fa2c25f7dc8372c0b7f7/.github/workflows/build-and-push-to-ecr.yml#L102)). We have [introduced a regex that parses out an optional `path` value](https://github.com/glg-public/gds-cc-screamer/pull/244/files#diff-34915535e7d99fde40dc5d14ee48b5bbc77bc552b4c702eb9b9be22798074f7aR5) that we can expose later while still checking to make sure this is a valid path. [The image value is then later checked if it exists in ECR to truly validate the …
=> initial support of sub ecr images within gh repositories

README.md, checks/china-forward-host-headers.js, checks/index.js, checks/validate-capacity.js, checks/validate-cron.js, test/fixtures/capacity-custom-both, test/fixtures/capacity-custom-max, test/fixtures/capacity-custom-min, test/fixtures/capacity-default, test/validate-capacity.js
- The value of `ECS_TASK_MAX_CAPACITY` shall never less than `ECS_TASK_MIN_CAPACITY`
- We have default value, it will handle the default number as well.
- Unit test has been added
- Correct some code with the value passed to `results.path`
https://github.com/glg-public/gds-cc-screamer/issues/251
=> Add new check: Validate capacity
