checks/policy-json-valid.js
checks/secrets-in-orders.js
index.js
test/policy-json-valid.js
test/root-index.js
test/secrets-in-orders.js
typedefs.js

This includes the following updates and improvements:
- Will now propose a policy.json when needed
- Will propose adding a suffix to secret ARNs rather than adding a new statement block in some circumstances
- Proposes opening an issue on this repo when errors are encountered
- Falls back to issue comments when PR comments are outside the diff
- Reduced required permissions in policy.json to reflect a recent update

Updates and fixes

---

index.js
test/root-index.js
test/util.js
util.js

I pulled a lot of the primary operations (leaving comments, loading files, etc) out of the main `run()`, and made them functional code that lives in `./util.js`. This facilitates easier testing, and makes the main `run()` cleaner and easier to understand.

Functionalizing

---

checks/secrets-in-orders.js
test/util.js
util.js

Every comment left by this github action will now contain a link to open a bug report.
pre-fills out an issue:

Bug report links

---

checks/deployment-line.js
checks/healthcheck.js
checks/https-only.js
checks/index.js
checks/jwt-access-flags.js
checks/no-aws-secrets.js
checks/no-carriage-return.js
checks/no-debug-in-prod.js
checks/no-duplicate-exports.js
checks/no-out-of-scope-vars.js
checks/no-sourcing.js
checks/no-spaces-in-exports.js
checks/policy-json-valid.js
checks/secrets-in-orders.js
checks/secrets-json-valid.js
checks/security-mode.js
checks/service-name.js
checks/template.js
checks/use-cname.js
checks/valid-bash-substitution.js
index.js
module.js
package.json
util/github.js

By exposing this action as a module, I can use it directly in deployanator, thus eliminating the possibility of the two getting out of sync.

expose as module

---

checks/index.js
checks/no-reserved-vars.js
checks/secrets-json-valid.js
test/no-reserved-vars.js
test/no-restricted-vars.js
test/util/text.js
util/text.js

This introduces a new check to prevent reserved variables from being re-defined.

no reserved variables

---

action.yml
checks/index.js
checks/max-services-per-cluster.js
checks/no-reserved-vars.js
index.js
test/fixtures/cc1/test-service/orders
test/fixtures/cc1/test-service/policy.json
test/fixtures/cc1/test-service/secrets.json
test/fixtures/cc2/test-service/orders
test/fixtures/cc2/test-service/policy.json
test/fixtures/cc2/test-service/secrets.json
test/fixtures/cc2/test-service2/orders
test/fixtures/cc2/test-service2/policy.json
test/fixtures/cc2/test-service2/secrets.json
test/fixtures/cc5/test-service/orders
test/fixtures/cc5/test-service/policy.json
test/fixtures/cc5/test-service/secrets.json
test/fixtures/cc5/test-service2/orders
test/fixtures/cc5/test-service2/policy.json
test/fixtures/cc5/test-service2/secrets.json
test/fixtures/cc5/test-service3/orders
test/fixtures/cc5/test-service3/policy.json
test/fixtures/cc5/test-service3/secrets.json
test/fixtures/cc5/test-service4/orders
test/fixtures/cc5/test-service4/policy.json
test/fixtures/cc5/test-service4/secrets.json
test/fixtures/cc5/test-service5/orders
test/fixtures/cc5/test-service5/policy.json
test/fixtures/cc5/test-service5/secrets.json
test/max-services-per-cluster.js

This adds a new check to ensure that the max number of services per cluster is not exceeded

Max services per cluster

---

checks/fqdn-required.js
checks/index.js
test/fixtures/cluster-map.json
test/fqdn-required.js

This adds a new check that requires users to specify `GDS_FQDN`, which defines a preferred domain name.

Enforce fqdn

---

checks/deployment-line.js
checks/template.js
test/deployment-line.js

resolves #27
This extends the deployment line check to also check the existence of the requested resource. It uses deployinator to do this.

More deploy validation

---

checks/jwt-access-flags.js
checks/valid-templates-json.js
test/jwt-access-flags.js
util/generic.js

resolves #22 
This extends the functionality of the access flag check to verify the existence of specified roles

More access flag checking

---

checks/index.js
checks/secrets-exist.js
test/secrets-exist.js

If a deployinator connection is configured, this check will validate that all referenced secrets exist
resolves #42

add check for secrets existing

---

checks/jwt-access-flags.js
test/fixtures/public-orders
test/jwt-access-flags.js
util/github.js

resolves #46 
Handles undefined comment lines, and corrects some logic in validating access flags for public orders

fix bug in access flag checking

---

checks/ecs-scheduled-task-count.js
checks/index.js
checks/potential-secrets.js
test/ecs-scheduled-task-count.js
test/potential-secrets.js

resolves #47 
Adds a check to validate `ECS_SCHEDULED_TASK_COUNT`

Ecs task count limit

---

checks/valid-bash-substitution.js
test/valid-bash-substitution.js

ignore CMD bash substitutions

---

checks/index.js
checks/jobs-only-on-jobs.js
checks/security-mode.js
test/jobs-only-on-jobs.js
util/generic.js
util/index.js

resolves #74 
This enforces only deploying services to service clusters, and only deploying jobs to jobs clusters

Jobs only on jobs

---

checks/potential-secrets.js
test/potential-secrets.js

add check for email list

---

README.md
checks/index.js
checks/valid-betas.js
test/valid-betas.js

add check to validate betas

---

checks/potential-secrets.js
test/potential-secrets.js

In addition to checking if a string is a url, we now also check if a string simply contains a url. this resolves #120 , and other similar issues.

handle strings that contain urls

---

test/jwt-access-flags.js
util/generic.js

This fixes the following issue:
by ignoring unknown claims specifically for `role-glg:2147483647`.  
This PR also provides tests for this case

allow role-glg:2147483647

---

checks/no-out-of-scope-vars.js
checks/security-mode.js
checks/valid-bash-substitution.js
test/no-out-of-scope-vars.js
test/security-mode.js
test/valid-bash-substitution.js

resolves #127 
resolves #128 
resolves #129

Htpasswd issues

---

checks/valid-templates-json.js

don't display undefined message

---

checks/use-cname.js

Fixing an error found here: https://github.com/glg/gds.clusterconfig.s01/runs/5205949669?check_suite_focus=true

move scope of variable

---

checks/deployment-line.js
test/deployment-line.js

fix unexpected parsing the tag in deckerdeploy/jobdeploy

---

checks/secrets-json-valid.js
test/secrets-json-valid.js

resolves #157
Blocks when a secret name is formatted such that it will definitely cause a problem deploying.

handle 6 character secret suffix

---

checks/validate-cron.js
test/fixtures/cron-orders-comment-at-top
test/validate-cron.js

resolves #192 
This one is just silly. The fix is using `>=` instead of `>`.

handle cron at the top of orders

---

checks/policy-json-valid.js

kinda feel like my linter should have caught this one

---

checks/max-services-per-cluster.js
package.json
test/max-services-per-cluster.js

resolves #220 by excluding jobs from the max services count.

only include services in the max service count

---

checks/deployment-line.js

Fixes #248 
Before:
After
This was a regression that wasn't caught by tests.  Will be adding a test but want this fix out.

Fix the regexes to handle tags with dashes
